# Generated by Django 3.1.7 on 2021-03-06 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Ingredient', max_length=50, null=True, verbose_name='Ingredient Name')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=50, null=True, verbose_name='Recipe Name')),
                ('description', models.TextField(default='Default Description', null=True, verbose_name='Description')),
                ('favourite', models.BooleanField(default=False, null=True, verbose_name='Favourite')),
                ('ingredient', models.ForeignKey(default='Default Ingredient', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.ingredient')),
            ],
        ),
    ]
