# Generated by Django 3.1.7 on 2021-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourite',
            field=models.BooleanField(default=False, verbose_name='Favourite'),
        ),
    ]
